#include <stdio.h>
void hailstones(int n);

int main()
{
    int num;
    scanf("%d", &num);
    printf("Hailstones generated by %d:\n", num);

    hailstones(num);
    return 0;
}

void hailstones(int n)
{
    int i;
    printf("%d ", n);
    for (i = 0; n > 0; i++)
    {
        if (n > 1)
        {
            if (n % 2 == 0)
                n /= 2;
            else
                n = n * 3 + 1;
            printf("%d ", n);
        }
        else
            n = 0;

        if (i == 4 || (i % 5 == 0 && i > 5))
            printf("\n");
    }
    printf("\nNumber of hailstones generated: %d", i);
}